package casebycase;

import org.junit.BeforeClass;
import pdca.quiz.model.QuizVo;

import java.util.ArrayList;
import java.util.List;

/**
 * Created by SSaMKJ on 2015-11-19.
 */
public class QuizDataTest {

    @BeforeClass
    public void set(){

        List<QuizVo> quizDatas = new ArrayList<QuizVo>();
        QuizVo quizVo = null;
        quizVo = new QuizVo();
        quizVo.setSeq(1l);
        quizVo.setEn_myid(1l);
        quizVo.setKo_myid(1l);
        quizVo.setEn_word("belated");
        quizVo.setKo_word("때늦은");
        quizDatas.add(quizVo);
        quizVo = new QuizVo();
        quizVo.setSeq(2l);
        quizVo.setEn_myid(2l);
        quizVo.setKo_myid(2l);
        quizVo.setEn_word("disclose");
        quizVo.setKo_word("밝히다, 드러내다");
        quizDatas.add(quizVo);
        quizVo = new QuizVo();
        quizVo.setSeq(3l);
        quizVo.setEn_myid(3l);
        quizVo.setKo_myid(3l);
        quizVo.setEn_word("extreme measure");
        quizVo.setKo_word("극단적인 조치");
        quizDatas.add(quizVo);
        quizVo = new QuizVo();
        quizVo.setSeq(4l);
        quizVo.setEn_myid(4l);
        quizVo.setKo_myid(4l);
        quizVo.setEn_word("fulfill");
        quizVo.setKo_word("이행하다");
        quizDatas.add(quizVo);
        quizVo = new QuizVo();
        quizVo.setSeq(5l);
        quizVo.setEn_myid(5l);
        quizVo.setKo_myid(5l);
        quizVo.setEn_word("contrary");
        quizVo.setKo_word("반대되는");
        quizDatas.add(quizVo);
        quizVo = new QuizVo();
        quizVo.setSeq(6l);
        quizVo.setEn_myid(6l);
        quizVo.setKo_myid(6l);
        quizVo.setEn_word("intangible");
        quizVo.setKo_word("무형의");
        quizDatas.add(quizVo);
        quizVo = new QuizVo();
        quizVo.setSeq(7l);
        quizVo.setEn_myid(7l);
        quizVo.setKo_myid(7l);
        quizVo.setEn_word("owing to");
        quizVo.setKo_word("~때문에");
        quizDatas.add(quizVo);
        quizVo = new QuizVo();
        quizVo.setSeq(8l);
        quizVo.setEn_myid(8l);
        quizVo.setKo_myid(8l);
        quizVo.setEn_word("reconcile");
        quizVo.setKo_word("화해시키다");
        quizDatas.add(quizVo);
        quizVo = new QuizVo();
        quizVo.setSeq(9l);
        quizVo.setEn_myid(9l);
        quizVo.setKo_myid(9l);
        quizVo.setEn_word("tedious");
        quizVo.setKo_word("지루한");
        quizDatas.add(quizVo);
        quizVo = new QuizVo();
        quizVo.setSeq(10l);
        quizVo.setEn_myid(10l);
        quizVo.setKo_myid(10l);
        quizVo.setEn_word("submit");
        quizVo.setKo_word("제출하다");
        quizDatas.add(quizVo);
        quizVo = new QuizVo();
        quizVo.setSeq(11l);
        quizVo.setEn_myid(11l);
        quizVo.setKo_myid(11l);
        quizVo.setEn_word("provision");
        quizVo.setKo_word("조항, 공급");
        quizDatas.add(quizVo);
        quizVo = new QuizVo();
        quizVo.setSeq(12l);
        quizVo.setEn_myid(12l);
        quizVo.setKo_myid(12l);
        quizVo.setEn_word("rigorous");
        quizVo.setKo_word("엄격한, 혹독한");
        quizDatas.add(quizVo);
        quizVo = new QuizVo();
        quizVo.setSeq(13l);
        quizVo.setEn_myid(13l);
        quizVo.setKo_myid(13l);
        quizVo.setEn_word("tuition");
        quizVo.setKo_word("수업료");
        quizDatas.add(quizVo);
        quizVo = new QuizVo();
        quizVo.setSeq(14l);
        quizVo.setEn_myid(14l);
        quizVo.setKo_myid(14l);
        quizVo.setEn_word("prominet");
        quizVo.setKo_word("두드러진");
        quizDatas.add(quizVo);
        quizVo = new QuizVo();
        quizVo.setSeq(15l);
        quizVo.setEn_myid(15l);
        quizVo.setKo_myid(15l);
        quizVo.setEn_word("novice");
        quizVo.setKo_word("초보자");
        quizDatas.add(quizVo);
        quizVo = new QuizVo();
        quizVo.setSeq(16l);
        quizVo.setEn_myid(16l);
        quizVo.setKo_myid(16l);
        quizVo.setEn_word("liable");
        quizVo.setKo_word("~하기 쉬운, ~할 것 같은");
        quizDatas.add(quizVo);
        quizVo = new QuizVo();
        quizVo.setSeq(17l);
        quizVo.setEn_myid(17l);
        quizVo.setKo_myid(17l);
        quizVo.setEn_word("patronize");
        quizVo.setKo_word("단골로 삼다");
        quizDatas.add(quizVo);
        quizVo = new QuizVo();
        quizVo.setSeq(18l);
        quizVo.setEn_myid(18l);
        quizVo.setKo_myid(18l);
        quizVo.setEn_word("implication");
        quizVo.setKo_word("밀접한 관계, 관련, 암시");
        quizDatas.add(quizVo);
        quizVo = new QuizVo();
        quizVo.setSeq(19l);
        quizVo.setEn_myid(19l);
        quizVo.setKo_myid(19l);
        quizVo.setEn_word("endowment");
        quizVo.setKo_word("기증, 기부");
        quizDatas.add(quizVo);
        quizVo = new QuizVo();
        quizVo.setSeq(20l);
        quizVo.setEn_myid(20l);
        quizVo.setKo_myid(20l);
        quizVo.setEn_word("discourteous");
        quizVo.setKo_word("무례한");
        quizDatas.add(quizVo);

    }
}
